mongodb:
  host: "127.0.0.1"
  port: 27017
  db_name: 'wren_db'
  articles: 'articles'
  podcasts: 'podcasts'
  videos: 'videos'

kafka:
  host: "127.0.0.1"
  port: 9092
  Articles: 'articles'
  Podcasts: 'podcasts'
  Videos: 'videos'