mongodb:
  host: "172.19.0.2"
  port: 27017
  db_name: '_wren_db'
  articles: 'articles'
  podcasts: 'podcasts'
  videos: 'videos'

kafka:
  host: "172.19.0.4"
  port: 9092
  Articles: 'articles'
  Podcasts: 'podcasts'
  Videos: 'videos'